// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCACDF0cSP7DQvgylBb6T5fwq6k4s0uqmg',
    appId: '1:534526720760:web:5b4dd2d6caa6e5f86a190d',
    messagingSenderId: '534526720760',
    projectId: 'instagram-clone-c5688',
    authDomain: 'instagram-clone-c5688.firebaseapp.com',
    storageBucket: 'instagram-clone-c5688.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRcyMG_BJbLa5ks0hfLlySf_0HjmXKG-U',
    appId: '1:534526720760:android:68a439336077ca036a190d',
    messagingSenderId: '534526720760',
    projectId: 'instagram-clone-c5688',
    storageBucket: 'instagram-clone-c5688.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG5k5rOOn_FKOTIg5Yjj944czb_CcIIRI',
    appId: '1:534526720760:ios:92188cab7b0d5f056a190d',
    messagingSenderId: '534526720760',
    projectId: 'instagram-clone-c5688',
    storageBucket: 'instagram-clone-c5688.appspot.com',
    iosBundleId: 'com.example.instagramClonee',
  );
}
